on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'test bot' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $USER
          echo $AUTHOR
        env:
          USER: ${{ github.event.comment.user.type }}
          AUTHOR: ${{ github.event.comment.author_association }}
